### PR TITLE
Implement parsing XML document into xmerl format

### PR DESCRIPTION
**Pull request by qcam**

### CODE REVIEW

**Comment by stevedomin** [comment]
@qcam this PR is 👌, can't wait for it to land in master. Was looking into adding xpath support to saxy but it looks like this would do the job for now.

**Comment by qcam** [comment]
@stevedomin I'm still very struggling with the pros and cons of this implementation. The upside is that we can avoid writing code by leveraging on Erlang `xmerl_xpath`. The downside is all about dynamic atoms generation and `binary <=> charlist` conversions, which make this PR less appealing.

I have been looking into alternative solutions including porting `xmerl_xpath` to Saxy but I don't have time to proceed with them.

Please feel free to share your thoughts and give it a go if you have better ideas.

**Comment by stevedomin** [comment]
That was going to be my first option as well but it's clearly not a small endeavour.

100% agree on the downsides but at the same time I think that having xpath support would be really nice and this feels like the fastest way to get it. I did some unscientific benchmarking and your library is still 3 or 4 times faster than xmerl in this case.

**Comment by qcam** [comment]
That is fair. I will polish and merge the PR then. This will be our last step towards 1.0 🎉.

**Comment by stevedomin** [comment]
🎉 

Also one small thing to note: because this code lives in its own module `Saxy.Xmerl` it would be very easy to add proper xpath support to Saxy and deprecate the `Saxy.Xmerl` module. Or at least stop supporting it and encourage people to move to the new module if they want xpath support.

**Comment by stevedomin** [comment]
🎉 🎉 🎉 thanks @qcam!!

**Pull request merged**
