### PR TITLE
Parsing little by little

### PR DESCRIPTION
**Pull request by manuel-rubio**
Instead of fail when a document like this is passed:
```
<document id="1">...</document>
<document id="2">...</document>
```
It's parsing only the first tag, and returning something like this:
```
{:ok, %Xmlel{...}, "<document=\"2\">...</document>"}
```

### CODE REVIEW

**Comment by qcam** [comment]
Thanks for the PR. According to the XML 1.0 specification, a well-formed XML document should contain exactly one root element.

https://www.w3.org/TR/xml/#sec-well-formed

I'd prefer to fail if there is more than one root element.

**Comment by qcam** [comment]
Gentle ping @manuel-rubio.

**Comment by manuel-rubio** [comment]
> Thanks for the PR. According to the XML 1.0 specification, a well-formed XML document should contain exactly one root element.
> 
> https://www.w3.org/TR/xml/#sec-well-formed
> 
> I'd prefer to fail if there is more than one root element.

Yes, I know, that's only because I'm parsing partially an XMPP transmission so, sometimes, the TCP connection is giving me two XML chunks, I have no way to split them so, I prefer to parse correctly the first, return the second as extra data and then continue parsing the second one.

**Comment by qcam** [comment]
I'd propose to handle this in the event handler. The idea could be keeping a stack of tags being parsed. Then if we see the stack is empty when we receive an `:end_element` event which empty stack, it means that the document has been successfully parsed. In that event, we can return something like `{:stop_return, state}` to tell the parser to stop and return the state and the rest of the document? `{:stop_return, state}` needs to be introduced though.

I think this will minimize the changes on the APIs. WDYT?

**Comment by manuel-rubio** [comment]
sounds great! @qcam

**Comment by qcam** [comment]
Closing in favor of #66.

**Pull request closed without merging**
