### PR TITLE
Introduce an alternate map based parsed form

### PR DESCRIPTION
**Pull request by vanjabucic**
While SimpleForm can be useful, I find that a map based parser can be easier to use for naive/simplistic workloads.
Almost all xml parsers out there have a to_map operator (with standard caveats).
Also, it can be used as another example on how to build a custom event handler.

### CODE REVIEW

**Comment by qcam** [comment]
Hi @vanjabucic, thanks for such a wonderful PR (I really like how the decisions well documented and explained). While I'm pretty exciting with the idea, I recently learned of https://github.com/bennyhat/xml_json which implements some conventional approaches to convert XML to JSON/map. Would that cover the use case in your mind?

**Comment by vanjabucic** [comment]
Thanks for pointing out the other project that deals with different map representations, I was not aware of it.
It does provide nice examples on how to approach XML parsing into custom payloads.
Maybe it deserves a mention in the docs somewhere. Newcomers to the language (especially the FP aspect) would find SAX processing a daunting task. I know I always appreciated sample implementations.
Thanks again for your work on Saxy.

**Comment by qcam** [comment]
👍 Definitely I should mention `xml_json` in README. Also would you mind if I turn your work in the PR to a guide in https://github.com/qcam/saxy/tree/master/guides?

**Comment by vanjabucic** [comment]
Please do use it in any way you see fit, it was meant as an example/guide anyhow.

**Comment by qcam** [comment]
Mentioned at https://github.com/qcam/saxy/commit/5b427b94f517129e432d85871f9c3cd26fa67e90

**Pull request closed without merging**
