### PR TITLE
fix dialyxir

### PR DESCRIPTION
**Pull request by manuel-rubio**
Looks like that this small change fix the whole thing :-D

### CODE REVIEW

**Comment by qcam** [comment]
Oh thanks for the PR :). I think we should update the implementation of `Saxy.Builder` to match the expectation in the type spec instead.

**Comment by qcam** [comment]
Could you help to verify if #76 passes the check? Thanks!

**Comment by manuel-rubio** [comment]
oh! yes, better solution! #76 passed Dialyxir.

**Comment by qcam** [comment]
Awesome, many thanks for all the help again!

**Pull request closed without merging**
