### PR TITLE
Fix compilation warnings and test a wider range of Elixir versions

### PR DESCRIPTION
**Pull request by wkirschbaum**
Changes: 

- charlists changed to sigil syntax to fix warnings for the upcoming 1.17 elixir version
- test all supported versions of Elixir, including 1.11
- set the minimum Elixir version to 1.11

### CODE REVIEW

**Comment by tosie** [comment]
+1 for this. Can the failing be restarted, please? Seems like the runtime could not be set up:

```
Action fetch /builds/otp/ubuntu-22.04/builds.txt failed for mirror https://builds.hex.pm,/ with Error: Request timeout: /builds/otp/ubuntu-22.04/builds.txt
Error: Could not fetch /builds/otp/ubuntu-22.04/builds.txt from any hex.pm mirror
```

Source: https://github.com/qcam/saxy/actions/runs/8779914685/job/24577094671?pr=130

**Comment by wkirschbaum** [comment]
@tosie not from my side it appears, unless I push an empty commit

**Comment by tosie** [comment]
@qcam Can you take a look at this, please? Can we help in any way?

**Review by qcam — APPROVED** [review]

**Comment by qcam** [comment]
Thanks for fixing this.

**Pull request merged**
